# Let's give a name to this application
APPLICATION=first-app

# By default, this application is built for the native target.
BOARD ?= native

# The RIOT base directory is located at the same level as the exercises base
# directory.
RIOTBASE ?= $(CURDIR)/../../../RIOT

# This line includes all defined make targets (flash, term, etc) in the RIOT
# build system.
include $(RIOTBASE)/Makefile.include
