APPLICATION=first-thread

BOARD ?= native

RIOTBASE ?= $(CURDIR)/../../../../RIOT

# Add shell related modules here
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
