APPLICATION=shell

BOARD ?= b-l072z-lrwan1

RIOTBASE ?= $(CURDIR)/../../../../RIOT

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += hts221

include $(RIOTBASE)/Makefile.include
