APPLICATION=drivers-application

BOARD ?= b-l072z-lrwan1

USEMODULE += xtimer
USEMODULE += hts221
USEMODULE += lsm6dsl

DEVELHELP ?= 1

RIOTBASE ?= $(CURDIR)/../../../../RIOT

include $(RIOTBASE)/Makefile.include
