APPLICATION=rtc-application

BOARD ?= b-l072z-lrwan1

USEMODULE += xtimer

FEATURES_REQUIRED += periph_rtc

DEVELHELP ?= 1

RIOTBASE ?= $(CURDIR)/../../../../RIOT

include $(RIOTBASE)/Makefile.include
